Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -6,7 +6,7 @@ on:
       - master
 
 jobs:
-  build:
+  test:
     runs-on: ubuntu-latest
 
     steps:
@@ -25,7 +25,24 @@ jobs:
         run: npx eslint src/
 
       - name: Run tests
-        run: npm test || true
+        run: npm test || true # Continue even if tests fail
+
+  build:
+    needs: test
+    runs-on: ubuntu-latest
+    if: success() # Only run if the test job succeeded
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v2
+
+      - name: Set up Node.js
+        uses: actions/setup-node@v3
+        with:
+          node-version: 'lts/*'
+
+      - name: Install dependencies
+        run: npm install
 
       - name: Build project
         run: CI=false npm run build
@@ -42,6 +59,7 @@ jobs:
   deploy:
     needs: build
     runs-on: ubuntu-latest
+    if: success() # Only run if the build job succeeded
 
     steps:
       - name: Checkout repository
